FROM python:3.9

WORKDIR /mybackend

COPY ./requirements.txt /mybackend/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /mybackend/requirements.txt

COPY ./ /mybackend

CMD ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]